### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by cedeber** [jtenner/parcel-plugin-pegjs#1]
Hello, I wonder if you still maintain this package, as well as on npm?

If no, I would like to be able to update it with the stable version of pegjs (as on [this fork]( https://github.com/dundalek/parcel-plugin-pegjs)) and so upgrade the npm package as well, so that we don't have unnecessary duplicates.

Thanks a lot.

**Comment by jtenner** [comment]
Nope. I don't own the package on npm, however, I can update the package versions!

Give me a few hours and I'll get this working.

**Comment by cedeber** [comment]
Thanks.
But you are set as maintainer for https://www.npmjs.com/package/parcel-plugin-pegjs, aren't you?

**Comment by jtenner** [comment]
News to me! Looks like I should get on that :)

**Comment by cedeber** [comment]
Cool 👍

**Comment by jtenner** [comment]
@cedeber Would you mind installing the plugin and making sure it works on your end?

```
npm install --save-dev jtenner/parcel-plugin-pegjs
```

Would be a great help! Thanks.

**Comment by jtenner** [comment]
I think it might be better if the pegjs and parcel versions were `peerDependencies` actually.

**Comment by cedeber** [comment]
I will test, sure. Currently the [source](https://github.com/jtenner/parcel-plugin-pegjs/blob/f3bf4c9b42583e249c667cad12b9dbc16dccb6ab/src/PEGJSAsset.js#L1) still require `pegjs-dev`

**Comment by jtenner** [comment]
Forgot that. Whoops! Looks like this is all set now. Test again?

**Comment by jtenner** [comment]
I spun up a small project installing from github, and the grammar from the documentation page seems to compile just fine. Once you're all set, I'll publish to npm.

**Comment by cedeber** [comment]
I am building my app with Parcel and currently files related in the `main` property of `package.json` should be JS5. Unlike the `module` property which has to be ES6. In this condition, I think you should set `commonjs` instead of `es` for the [peg options](https://github.com/jtenner/parcel-plugin-pegjs/blob/6e7c20c311adf46dde83c3012a04a8c25d728499/src/PEGJSAsset.js#L12).

If I set it up with `commonjs`, by rewriting the installed node_modules, it works 👍

**Comment by jtenner** [comment]
I'm curious. Does the es option work with `import`?

**Comment by cedeber** [comment]
I am using TypeScript and I use `import parser from "foo.pegjs"`. It is compiled to ES2017 and transpiled to ES5 by Babel. It works as expected.

But, currently, the generated parser is an ES modules which is imported as a commonjs module by Parcel (because of the `main` behavior described above). So the `export` keyword raise an error in the bundle as this is not an ES module.

I hope it was clear 😅

**Comment by cedeber** [comment]
So, to answer your question, the `es` option should work if the module would have been treaten as an ES module, which is not the case currently, because most of npm modules are ES5. A bit of a shame, I agree, but ES Modules support by npm is still experimental.

So Parcel is waiting for ES5 for npm modules with the `main` property. In short: `require()` instead of `import/export`.

**Comment by jtenner** [comment]
Okay. Is there a way to determine which option I should use? Certainly I can make this change. I was just curious if it was possible to use the `es` option at all.

**Comment by cedeber** [comment]
I create a fork with what I had in mind: https://github.com/cedeber/parcel-plugin-pegjs.
There are 2 entries in package.json:
- `main` for `require` => es5
- `module` for `import/export` => es6

I test it in our Parcel workflow and it works. Can you maybe test with your es6 setup?

**Comment by jtenner** [comment]
Right. I was just curious if parcel gives us information about how the module is being imported. Chances are parcel prefers es5 and commonjs.

**Comment by cedeber** [comment]
So far I know, yes, Parcel is waiting for ES5 from npm modules.

**Comment by jtenner** [comment]
Alright @cedeber. Sorry for the wait! Let's try it again. Can you install via `npm install --save-dev jtenner/parcel-plugin-pegjs` and see if it works for you?

**Comment by cedeber** [comment]
Yes it works. But a last question ;) Shouldn't parcel-bundler be a peerDependencies instead of devDependencies here?

**Comment by jtenner** [comment]
I think it's fine as is. You aren't going to install `parcel-plugin-pegjs` without `parcel-bundler`. Besides, we shouldn't assume the version that the user is going to use (in case they need an old one for compatibility reasons.)

Not sure about leaving `pegjs` as a dependency here either. Thoughts?

**Comment by cedeber** [comment]
Yeah, you right.

You can set pegjs as peerDependencies then, for, more or less, the same reasons as above ;) With a minimal version to the current one, probably.

**Comment by jtenner** [comment]
Trying `npm install --save-peer package` results in a regular dependency, so I'll leave it as a devDependency. I updated the readme for proper usage and made sure the package version was bumped. Can you test one last time?

Once it's all set I'll publish to npm unless you think there are any other issues.

**Comment by cedeber** [comment]
Looks good to me. Thanks for the help.

**Comment by jtenner** [comment]
All set. Published to npm version `0.0.2`
